models:
  stt_vosk:
    en: "models/stt_vosk/vosk-model-small-en-us-0.15"
    fr: "models/stt_vosk/vosk-model-small-fr-0.22"
  tts_piper:
    fr_upmc: "models/tts_piper/fr_FR-upmc-medium.onnx"
    fr_upmc_json: "models/tts_piper/fr_FR-upmc-medium.onnx.json"
    en_amy: "models/tts_piper/en_US-amy-medium.onnx"
    en_amy_json: "models/tts_piper/en_US-amy-medium.onnx.json"


testing:
  output_dir: "tests/output"
  run_integration_tests: true

# --- COMMANDES ROBOT QT ---
qt_robot:
  default_velocity: 20  # Vitesse par défaut (0-100)
  gestures:
    - "QT/hi"
    - "QT/bye"
    - "QT/wave"
    - "QT/nod"
    - "QT/shake_head"
    - "QT/thinking"
    - "QT/surprise"
    - "QT/angry"
    - "QT/kiss"
  emotions:
    - "QT/happy"
    - "QT/sad"
    - "QT/angry"
    - "QT/surprise"
    - "QT/neutral"